export type BoutiqueCategory =
  | "rtd"
  | "spiritueux"
  | "sans-alcool"
  | "accessoires";

export interface BoutiqueProduct {
  slug: string;
  name: string;
  boutiqueCategory: BoutiqueCategory;
  description: string;
  image: string | null;
  price: number;
  comparePrice?: number;
  volume?: string;
  abv?: string;
  wooUrl: string;
  saqAvailable: boolean;
  saqUrl?: string;
  isExclusive?: boolean;
  exclusiveLocation?: "magog" | "quebec" | "both";
  isBestseller?: boolean;
  isNew?: boolean;
  badge?: string;
  productPageSlug?: string;
}

export const BOUTIQUE_FILTER_LABELS: Record<BoutiqueCategory, string> = {
  rtd: "Cocktails prêts-à-boire",
  spiritueux: "Spiritueux",
  "sans-alcool": "Sans alcool",
  accessoires: "Accessoires & Sirops",
};

export const BOUTIQUE_FILTERS: BoutiqueCategory[] = [
  "rtd",
  "spiritueux",
  "sans-alcool",
  "accessoires",
];

const WOOCOMMERCE_BASE = "https://www.cherryriver.ca";
const WOO = (slug: string) => `${WOOCOMMERCE_BASE}/produit/${slug}/`;

export const BOUTIQUE_PRODUCTS: BoutiqueProduct[] = [
  // ─── COCKTAILS PRÊTS-À-BOIRE ────────────────────────────
  {
    slug: "gin-limonade-355",
    name: "Gin Limonade",
    boutiqueCategory: "rtd",
    description: "Gin Cherry River & limonade artisanale. Pétillant et rafraîchissant.",
    image: "/assets/products/cans/CherryRiver_GinLimon_355mL_FRAN.png",
    price: 3.49,
    volume: "355 ml",
    abv: "5%",
    wooUrl: WOO("gin-limonade-355ml"),
    saqAvailable: true,
    isBestseller: true,
    productPageSlug: "gin-limonade-355",
  },
  {
    slug: "orange-sanguine-framboises-355",
    name: "Orange Sanguine & Framboises",
    boutiqueCategory: "rtd",
    description: "L'intensité de l'orange sanguine mariée à la douceur des framboises.",
    image: "/assets/products/cans/CherryRiver_OrangeSang_355mL_FRAN.png",
    price: 3.49,
    volume: "355 ml",
    abv: "5%",
    wooUrl: WOO("orange-sanguine-framboises-355ml"),
    saqAvailable: true,
    isBestseller: true,
    productPageSlug: "orange-sanguine-framboises-355",
  },
  {
    slug: "tropical-rich-rum-punch",
    name: "Tropical Rich Rum Punch",
    boutiqueCategory: "rtd",
    description: "Punch tropical au rhum ambré, fruits exotiques et épices.",
    image: "/assets/products/TropicalRichRumPunch_750mL.png",
    price: 16.99,
    volume: "750 ml",
    abv: "10%",
    wooUrl: WOO("tropical-rich-rum-punch"),
    saqAvailable: false,
    isNew: true,
    productPageSlug: "tropical-rich-rum-punch",
  },

  // ─── SPIRITUEUX ──────────────────────────────────────────
  {
    slug: "b-gin-petits-fruits",
    name: "Gin Petits Fruits & Basilic",
    boutiqueCategory: "spiritueux",
    description: "Le gin signature Cherry River — baies canadiennes et basilic.",
    image: "/assets/products/CR_Gin_Berries_750mL.png",
    price: 39.99,
    volume: "750 ml",
    abv: "40%",
    wooUrl: WOO("gin-petits-fruits-basilic"),
    saqAvailable: true,
    saqUrl: "https://www.saq.com/fr/14682882",
    isBestseller: true,
    productPageSlug: "gin-petits-fruits-basilic",
  },
  {
    slug: "b-gin-pamplemousse",
    name: "Gin Pamplemousse Rose",
    boutiqueCategory: "spiritueux",
    description: "Délicatement fruité et floral, une vivacité de pamplemousse rose unique.",
    image: "/assets/products/CR_Gin_Pamplemousse_750mL.png",
    price: 39.99,
    volume: "750 ml",
    abv: "40%",
    wooUrl: WOO("gin-pamplemousse-rose"),
    saqAvailable: true,
    saqUrl: "https://www.saq.com/fr/14989833",
    productPageSlug: "gin-pamplemousse-rose",
  },
  {
    slug: "b-gin-framboise-lime",
    name: "Gin Framboise & Lime",
    boutiqueCategory: "spiritueux",
    description: "La vivacité des fruits rouges et des agrumes se marie au genièvre.",
    image: "/assets/products/CR_Gin_FramboiseLime_750mL.png",
    price: 39.99,
    volume: "750 ml",
    abv: "40%",
    wooUrl: WOO("gin-framboise-lime"),
    saqAvailable: true,
    saqUrl: "https://www.saq.com/fr/15311581",
    productPageSlug: "gin-framboise-lime",
  },
  {
    slug: "b-gin-lime-gingembre",
    name: "Gin Lime & Gingembre",
    boutiqueCategory: "spiritueux",
    description: "Notes vives de lime et gingembre pour cocktails épicés.",
    image: "/assets/products/CR_Gin_Lime_750mL.png",
    price: 39.99,
    volume: "750 ml",
    abv: "40%",
    wooUrl: WOO("gin-lime-gingembre"),
    saqAvailable: true,
    saqUrl: "https://www.saq.com/fr/14954876",
    productPageSlug: "gin-lime-gingembre",
  },
  {
    slug: "b-gin-litchi-tangerine",
    name: "Gin Litchi & Tangerine",
    boutiqueCategory: "spiritueux",
    description: "Arômes exotiques de litchi et tangerine. Cocktails élégants.",
    image: "/assets/products/CR_Tangerine_750mL.png",
    price: 39.99,
    volume: "750 ml",
    abv: "40%",
    wooUrl: WOO("gin-litchi-tangerine"),
    saqAvailable: true,
    saqUrl: "https://www.saq.com/fr/14989770",
    productPageSlug: "gin-litchi-tangerine",
  },
  {
    slug: "b-vodka-averse",
    name: "Vodka Averse Premium",
    boutiqueCategory: "spiritueux",
    description: "Pureté absolue. Distillée avec précision pour une expérience cristalline.",
    image: "/assets/products/Averse_Vodka_Premium_750mL.png",
    price: 34.99,
    volume: "750 ml",
    abv: "40%",
    wooUrl: WOO("vodka-original-premium"),
    saqAvailable: true,
    saqUrl: "https://www.saq.com/fr/15489099",
    productPageSlug: "vodka-averse-premium",
  },
  {
    slug: "b-vodka-erable",
    name: "Vodka Érable",
    boutiqueCategory: "spiritueux",
    description: "Subtilement sucrée aux notes d'érable authentique du Québec.",
    image: "/assets/products/CR_Vodka_Erable_750mL.png",
    price: 34.99,
    volume: "750 ml",
    abv: "40%",
    wooUrl: WOO("vodka-erable"),
    saqAvailable: true,
    saqUrl: "https://www.saq.com/fr/14064873",
    productPageSlug: "vodka-erable",
  },
  {
    slug: "b-rhum-ambre",
    name: "Rhum Ambré",
    boutiqueCategory: "spiritueux",
    description: "Notes riches et caramélisées, profondeur de caractère unique.",
    image: "/assets/products/CR_RhumAmbre_750mL.png",
    price: 36.99,
    volume: "750 ml",
    abv: "40%",
    wooUrl: WOO("rhum-ambre"),
    saqAvailable: true,
    saqUrl: "https://www.saq.com/fr/15303910",
    productPageSlug: "rhum-ambre",
  },
  {
    slug: "b-rhum-epice",
    name: "Rhum Épicé",
    boutiqueCategory: "spiritueux",
    description: "Épices chaudes, caractère corsé et enveloppant.",
    image: "/assets/products/CR_RhumEpice.png",
    price: 36.99,
    volume: "750 ml",
    abv: "40%",
    wooUrl: WOO("rhum-epice"),
    saqAvailable: true,
    saqUrl: "https://www.saq.com/fr/14954868",
    productPageSlug: "rhum-epice",
  },
  {
    slug: "b-tequila-silver",
    name: "Tequila Silver",
    boutiqueCategory: "spiritueux",
    description: "Pure et cristalline, idéale pour shots et cocktails classiques.",
    image: "/assets/products/CR_TequilaSilver_750mL.png",
    price: 38.99,
    volume: "750 ml",
    abv: "40%",
    saqUrl: "https://www.saq.com/fr/14954892",
    wooUrl: WOO("tequila-silver"),
    saqAvailable: false,
    productPageSlug: "tequila-silver",
  },
  {
    slug: "b-opemiska-boreal",
    name: "Opemiska Gin Boréal",
    boutiqueCategory: "spiritueux",
    description: "Botaniques nordiques, baies sauvages et épinette noire.",
    image: "/assets/products/Ope_Gin_Boreal_750mL.png",
    price: 44.99,
    volume: "750 ml",
    abv: "43%",
    saqUrl: "https://www.saq.com/fr/14545132",
    wooUrl: WOO("opemiska-gin-boreal"),
    saqAvailable: false,
    isNew: true,
    productPageSlug: "opemiska-gin-boreal",
  },
  {
    slug: "b-opemiska-bleuets",
    name: "Opemiska Bleuets",
    boutiqueCategory: "spiritueux",
    description: "L'essence des bleuets sauvages du Québec en gin nordique.",
    image: "/assets/products/Ope_Bleuets_750mL.png",
    price: 44.99,
    volume: "750 ml",
    abv: "40%",
    wooUrl: WOO("opemiska-gin-boreal-bleuets"),
    saqAvailable: false,
    productPageSlug: "opemiska-bleuets",
  },
  {
    slug: "b-opemiska-fraise",
    name: "Opemiska Fraise",
    boutiqueCategory: "spiritueux",
    description: "Fraises d'été du Québec et botaniques boréaux.",
    image: "/assets/products/Ope_Fraise_750mL.png",
    price: 44.99,
    volume: "750 ml",
    abv: "40%",
    saqUrl: "https://www.saq.com/fr/15095284",
    wooUrl: WOO("opemiska-gin-boreal-fraises"),
    saqAvailable: false,
    productPageSlug: "opemiska-fraise",
  },
  {
    slug: "b-opemiska-liqueur-whisky",
    name: "Opemiska Liqueur de Whisky",
    boutiqueCategory: "spiritueux",
    description: "Whisky artisanal, caramel, vanille et bois fumé.",
    image: "/assets/products/Ope_LiqueurWhisky_750mL.png",
    price: 39.99,
    volume: "750 ml",
    abv: "30%",
    saqUrl: "https://www.saq.com/fr/15303872",
    wooUrl: WOO("opemiska-liqueur-de-whisky-a-lerable"),
    saqAvailable: false,
    productPageSlug: "opemiska-liqueur-whisky",
  },

  // ─── SANS ALCOOL ─────────────────────────────────────────
  {
    slug: "b-gin-sans-alcool",
    name: "Gin Petits Fruits Sans Alcool",
    boutiqueCategory: "sans-alcool",
    description: "Toute la complexité aromatique, sans l'alcool. Cocktails sans compromis.",
    image: "/assets/products/CR_Gin_Berries_SANS_ALCOOL_750mL.png",
    price: 29.99,
    volume: "750 ml",
    abv: "0%",
    wooUrl: WOO("gin-petits-fruits-basilic-sans-alcool"),
    saqAvailable: false,
    isNew: true,
    productPageSlug: "gin-sans-alcool",
  },
  {
    slug: "b-limonade-vodka",
    name: "Limonade Vodka Citron Vert",
    boutiqueCategory: "rtd",
    description: "Limonade non pétillante à la vodka et citron vert. Prête à servir.",
    image: "/assets/products/cans-na/Limonade_Non-petillante_Fran.png",
    price: 3.49,
    volume: "355 ml",
    abv: "5%",
    wooUrl: WOO("limonade-vodka-citron-vert"),
    saqAvailable: false,
    productPageSlug: "limonade-vodka-citron-vert",
  },

  {
    slug: "b-amaretto-sour-sa",
    name: "Amaretto Sour Sans Alcool",
    boutiqueCategory: "sans-alcool",
    description: "Amande, agrumes et douceur — sans une goutte d'alcool.",
    image: "/assets/products/cans-na/CR_AmarettoSour_355mL_SANS_ALCOOL_FRAN.png",
    price: 3.49,
    volume: "355 ml",
    abv: "0%",
    wooUrl: WOO("mocktail-amarette-sour-pret-a-boire-sans-alcool"),
    saqAvailable: false,
    productPageSlug: "amaretto-sour-sans-alcool",
  },
  {
    slug: "b-cosmo-sa",
    name: "Cosmopolitan Sans Alcool",
    boutiqueCategory: "sans-alcool",
    description: "Canneberge, lime et agrumes. Le classique revisité.",
    image: "/assets/products/cans-na/CR_Cosmo_355mL_SANS_ALCOOL_FRAN.png",
    price: 3.49,
    volume: "355 ml",
    abv: "0%",
    wooUrl: WOO("mocktail-cosmo-pret-a-boire-sans-alcool"),
    saqAvailable: false,
    productPageSlug: "cosmopolitan-sans-alcool",
  },
  {
    slug: "b-margarita-sa",
    name: "Margarita Sans Alcool",
    boutiqueCategory: "sans-alcool",
    description: "Lime, sel et fraîcheur festive en version zéro alcool.",
    image: "/assets/products/cans-na/CR_Margarita_355mL_SANS_ALCOOL_FRAN.png",
    price: 3.49,
    volume: "355 ml",
    abv: "0%",
    wooUrl: WOO("mocktail-margarita-pret-a-boire-sans-alcool"),
    saqAvailable: false,
    productPageSlug: "margarita-sans-alcool",
  },
  {
    slug: "b-melon-eau-lime-sa",
    name: "Melon, Eau & Lime Sans Alcool",
    boutiqueCategory: "sans-alcool",
    description: "Melon d'eau frais et lime vive. Désaltérant et léger.",
    image: "/assets/products/cans-na/CR_MelonEauLime_355mL_SANS_ALCOOL_FRAN.png",
    price: 3.49,
    volume: "355 ml",
    abv: "0%",
    wooUrl: WOO("mocktail-melon-deau-et-lime-pret-a-boire-sans-alcool"),
    saqAvailable: false,
    productPageSlug: "melon-eau-lime-sans-alcool",
  },
  {
    slug: "b-mojito-sa",
    name: "Mojito Sans Alcool",
    boutiqueCategory: "sans-alcool",
    description: "Menthe fraîche, lime et bulles. Le classique sans alcool.",
    image: "/assets/products/cans-na/CR_Mojito_355mL_SANS_ALCOOL_FRAN.png",
    price: 3.49,
    volume: "355 ml",
    abv: "0%",
    wooUrl: WOO("mocktail-mojito-pret-a-boire-sans-alcool"),
    saqAvailable: false,
    productPageSlug: "mojito-sans-alcool",
  },
  {
    slug: "b-orange-sanguine-sa",
    name: "Orange Sanguine Sans Alcool",
    boutiqueCategory: "sans-alcool",
    description: "L'intensité de l'orange sanguine en mocktail vibrant.",
    image: "/assets/products/cans-na/CR_OrangeSanguine_355mL_SANS_ALCOOL_FRAN.png",
    price: 3.49,
    volume: "355 ml",
    abv: "0%",
    wooUrl: WOO("mocktail-orange-sanguine-pret-a-boire-sans-alcool"),
    saqAvailable: false,
    productPageSlug: "orange-sanguine-sans-alcool",
  },
  {
    slug: "b-sangria-rouge-sa",
    name: "Sangria Rouge Sans Alcool",
    boutiqueCategory: "sans-alcool",
    description: "Fruits rouges, épices douces et fraîcheur festive.",
    image: "/assets/products/cans-na/CR_SangriaRouge_355mL_SANS_ALCOOL_FRAN.png",
    price: 3.49,
    volume: "355 ml",
    abv: "0%",
    wooUrl: WOO("mocktail-sangria-rouge-pret-a-boire-sans-alcool"),
    saqAvailable: false,
    productPageSlug: "sangria-rouge-sans-alcool",
  },
  {
    slug: "b-paloma-sa",
    name: "Mocktail Paloma Sans Alcool",
    boutiqueCategory: "sans-alcool",
    description: "Pamplemousse rose et lime. Rafraîchissant sans alcool.",
    image: "/assets/products/cans-na/CR_MocktailPaloma_355mL_SANS_ALCOOL_FRAN.png",
    price: 3.49,
    volume: "355 ml",
    abv: "0%",
    wooUrl: WOO("mocktail-paloma-pret-a-boire-sans-alcool"),
    saqAvailable: false,
    productPageSlug: "paloma-sans-alcool",
  },
  {
    slug: "b-petits-fruits-sa",
    name: "Mocktail Petits Fruits Sans Alcool",
    boutiqueCategory: "sans-alcool",
    description: "Bleuets, framboises et mûres en mocktail pétillant.",
    image: "/assets/products/cans-na/CR_MocktailPetitsFruits_355mL_SANS_ALCOOL_FRAN.png",
    price: 3.49,
    volume: "355 ml",
    abv: "0%",
    wooUrl: WOO("mocktail-petits-fruits-et-basilic-pret-a-boire-sans-alcool"),
    saqAvailable: false,
    productPageSlug: "petits-fruits-sans-alcool",
  },

  // ─── ACCESSOIRES & SIROPS ───────────────────────────────
  {
    slug: "b-sirop-simple",
    name: "Sirop Simple Cherry River",
    boutiqueCategory: "accessoires",
    description: "Le sirop de base essentiel pour tous vos cocktails artisanaux.",
    image: null,
    price: 12.99,
    volume: "500 ml",
    wooUrl: WOO("sirop-simple-de-sucre-de-canne"),
    saqAvailable: false,
  },
  {
    slug: "b-sirop-gingembre",
    name: "Sirop de Gingembre",
    boutiqueCategory: "accessoires",
    description: "Gingembre frais infusé pour cocktails piquants et rafraîchissants.",
    image: null,
    price: 14.99,
    volume: "500 ml",
    wooUrl: WOO("sirop-simple-the-vert-gingembre"),
    saqAvailable: false,
  },
  {
    slug: "b-coffret-decouverte",
    name: "Coffret Découverte Gin",
    boutiqueCategory: "accessoires",
    description: "3 gins Cherry River en format 200 ml — le cadeau parfait pour les amateurs.",
    image: null,
    price: 49.99,
    wooUrl: WOO("coffret-decouverte-gin"),
    saqAvailable: false,
    badge: "COFFRET",
  },
  {
    slug: "b-jigger-cherry-river",
    name: "Jigger Cherry River",
    boutiqueCategory: "accessoires",
    description: "Jigger double face en acier inoxydable gravé Cherry River. 1 oz / 2 oz.",
    image: "/assets/boutique/doseur_Silver.png",
    price: 18.99,
    wooUrl: WOO("jiggers"),
    saqAvailable: false,
  },
  {
    slug: "b-shaker-cherry-river",
    name: "Shaker Boston Cherry River",
    boutiqueCategory: "accessoires",
    description: "Shaker Boston professionnel en acier inoxydable avec logo gravé.",
    image: "/assets/boutique/Shaker_Noir.png",
    price: 34.99,
    wooUrl: WOO("shaker-a-cocktail-en-acier-inoxydable"),
    saqAvailable: false,
  },
];

/* ─── Exclusivités distillerie (non disponibles en ligne) ─── */

export const EXCLUSIVE_PRODUCTS: BoutiqueProduct[] = [
  {
    slug: "x-creme-coaticook",
    name: "Crème Alcoolisée de Crème Glacée Coaticook",
    boutiqueCategory: "spiritueux",
    description: "Crème alcoolisée onctueuse à base de crème glacée de la Laiterie de Coaticook. Le Québec en bouteille.",
    image: "/assets/products/Coaticook_Vanille_750mL.png",
    price: 29.99,
    volume: "750 ml",
    abv: "16%",
    wooUrl: "",
    saqAvailable: false,
    isExclusive: true,
    exclusiveLocation: "both",
    isNew: true,
  },
  {
    slug: "x-liqueur-amaretto",
    name: "Liqueur d'Amaretto",
    boutiqueCategory: "spiritueux",
    description: "Amandes grillées et vanille. Idéal pour cocktails ou digestif.",
    image: "/assets/images/scraped/products/CR_Amaretto_1.jpg",
    price: 32.99,
    volume: "750 ml",
    abv: "25%",
    wooUrl: "",
    saqAvailable: false,
    isExclusive: true,
    exclusiveLocation: "magog",
  },
  {
    slug: "x-liqueur-cafe",
    name: "Liqueur de Café",
    boutiqueCategory: "spiritueux",
    description: "Arômes intenses de grain torréfié. L'Espresso Martini parfait.",
    image: "/assets/images/scraped/products/CR_Liqueur_Cafe-1.jpg",
    price: 32.99,
    volume: "750 ml",
    abv: "25%",
    wooUrl: "",
    saqAvailable: false,
    isExclusive: true,
    exclusiveLocation: "magog",
  },
  {
    slug: "x-liqueur-orange",
    name: "Liqueur d'Orange",
    boutiqueCategory: "spiritueux",
    description: "Zestes d'orange et douceur subtile pour Cosmopolitan et Margarita.",
    image: "/assets/images/scraped/products/TRIPLESEC.jpg",
    price: 32.99,
    volume: "750 ml",
    abv: "25%",
    wooUrl: "",
    saqAvailable: false,
    isExclusive: true,
    exclusiveLocation: "quebec",
  },
  {
    slug: "x-liqueur-vanille",
    name: "Liqueur de Vanille",
    boutiqueCategory: "spiritueux",
    description: "Vanille pure, gourmande et chaleureuse.",
    image: "/assets/products/Coaticook_Vanille_750mL.png",
    price: 32.99,
    volume: "750 ml",
    abv: "25%",
    wooUrl: "",
    saqAvailable: false,
    isExclusive: true,
    exclusiveLocation: "both",
  },
  {
    slug: "x-bourbon-whiskey",
    name: "Bourbon Whiskey",
    boutiqueCategory: "spiritueux",
    description: "Notes boisées et vanillées. Un bourbon artisanal Cherry River.",
    image: "/assets/images/scraped/products/Bourbon-whiskey-cherry-river.png",
    price: 42.99,
    volume: "750 ml",
    abv: "40%",
    wooUrl: "",
    saqAvailable: false,
    isExclusive: true,
    exclusiveLocation: "magog",
  },
];
