export interface Product {
  slug: string;
  name: string;
  category: "spiritueux" | "liqueur" | "rtd" | "mocktail" | "mixer" | "opemiska" | "collaboration";
  subcategory?: string;
  description: string;
  tagline?: string;
  image: string | null;
  abv?: string;
  volume?: string;
  saqUrl?: string;
  websiteUrl?: string;
  videoMatchTags: string[];
  isFeatured?: boolean;
}

export const PRODUCTS_CATALOG: Product[] = [
  // ─── GINS ────────────────────────────────────────────────
  {
    slug: "gin-petits-fruits-basilic",
    name: "Gin Petits Fruits & Basilic",
    category: "spiritueux",
    subcategory: "gin",
    description: "Gin artisanal du Québec. Genièvre, baies canadiennes — mûre, bleuet, canneberge — et basilic. Finale équilibrée, distillé à Magog.",
    tagline: "Le gin artisanal signature Cherry River",
    image: "/assets/products/CR_Gin_Berries_750mL.png",
    abv: "40%",
    volume: "750 ml",
    websiteUrl: "https://www.cherryriver.ca/spiritueux/gin-petits-fruits-basilic/",
    saqUrl: "https://www.saq.com/fr/14682882",
    videoMatchTags: ["Gin Petits Fruits & Basilic", "Gin"],
    isFeatured: true,
  },
  {
    slug: "gin-pamplemousse-rose",
    name: "Gin Pamplemousse Rose",
    category: "spiritueux",
    subcategory: "gin",
    description: "Délicatement fruité et floral, idéal pour cocktails rafraîchissants. Le pamplemousse rose apporte une vivacité unique à ce gin artisanal.",
    image: "/assets/products/CR_Gin_Pamplemousse_750mL.png",
    abv: "40%",
    volume: "750 ml",
    websiteUrl: "https://www.cherryriver.ca/spiritueux/gin-pamplemousse-rose/",
    saqUrl: "https://www.saq.com/fr/14989833",
    videoMatchTags: ["Gin Pamplemousse", "Gin"],
  },
  {
    slug: "gin-framboise-lime",
    name: "Gin Framboise & Lime",
    category: "spiritueux",
    subcategory: "gin",
    description: "La vivacité des fruits rouges et des agrumes se marie à la rondeur du genièvre. Idéal en cocktail rafraîchissant.",
    image: "/assets/products/CR_Gin_FramboiseLime_750mL.png",
    abv: "40%",
    volume: "750 ml",
    websiteUrl: "https://www.cherryriver.ca/spiritueux/gin-framboise-lime/",
    saqUrl: "https://www.saq.com/fr/15311581",
    videoMatchTags: ["Gin Framboise & Lime", "Gin"],
  },
  {
    slug: "gin-lime-gingembre",
    name: "Gin Lime & Gingembre",
    category: "spiritueux",
    subcategory: "gin",
    description: "Notes vives de lime et piquantes de gingembre. Parfait pour cocktails épicés et rafraîchissants.",
    image: "/assets/products/CR_Gin_Lime_750mL.png",
    abv: "40%",
    volume: "750 ml",
    websiteUrl: "https://www.cherryriver.ca/spiritueux/gin-lime-gingembre/",
    saqUrl: "https://www.saq.com/fr/14954876",
    videoMatchTags: ["Gin Lime", "Gin"],
  },
  {
    slug: "gin-litchi-tangerine",
    name: "Gin Litchi & Tangerine",
    category: "spiritueux",
    subcategory: "gin",
    description: "Arômes fruités et exotiques de litchi et tangerine. Parfait pour cocktails élégants et surprenants.",
    image: "/assets/products/CR_Tangerine_750mL.png",
    abv: "40%",
    volume: "750 ml",
    websiteUrl: "https://www.cherryriver.ca/spiritueux/gin-litchi-tangerine/",
    saqUrl: "https://www.saq.com/fr/14989770",
    videoMatchTags: ["Gin Litchi", "Gin"],
  },
  {
    slug: "gin-floral",
    name: "Gin Floral",
    category: "spiritueux",
    subcategory: "gin",
    description: "Notes florales et fruitées de pamplemousse, litchi et fleurs sauvages. Parfait pour cocktails sophistiqués.",
    image: null,
    abv: "40%",
    volume: "750 ml",
    websiteUrl: "https://www.cherryriver.ca/spiritueux/gin-floral/",
    saqUrl: "https://www.saq.com/fr/14682891",
    videoMatchTags: ["Gin Floral", "Gin"],
  },
  {
    slug: "dry-gin",
    name: "Dry Gin",
    category: "spiritueux",
    subcategory: "gin",
    description: "London dry complexe, aux arômes de genièvre, citron amer, coriandre et botaniques sauvages du Québec comme le thé du Labrador.",
    image: "/assets/products/CR_DryGin_750mL.png",
    abv: "40%",
    volume: "750 ml",
    websiteUrl: "https://www.cherryriver.ca/spiritueux/dry-gin/",
    saqUrl: "https://www.saq.com/fr/14561781",
    videoMatchTags: ["Dry Gin", "Gin"],
  },
  {
    slug: "gin-sans-alcool",
    name: "Gin Petits Fruits Sans Alcool",
    category: "mocktail",
    subcategory: "gin",
    description: "Toute la complexité aromatique du Gin Petits Fruits & Basilic, sans l'alcool. Parfait pour des cocktails sans compromis.",
    image: "/assets/products/CR_Gin_Berries_SANS_ALCOOL_750mL.png",
    abv: "0%",
    volume: "750 ml",
    videoMatchTags: ["Mocktail", "Gin"],
  },

  // ─── VODKAS ──────────────────────────────────────────────
  {
    slug: "vodka-averse-premium",
    name: "Vodka Averse Premium",
    category: "spiritueux",
    subcategory: "vodka",
    description: "Toute en pureté et finesse. Distillée avec précision pour une expérience cristalline, parfaite en cocktail classique ou en dégustation.",
    tagline: "Pureté absolue",
    image: "/assets/products/Averse_Vodka_Premium_750mL.png",
    abv: "40%",
    volume: "750 ml",
    websiteUrl: "https://www.cherryriver.ca/spiritueux/vodka-original-premium/",
    saqUrl: "https://www.saq.com/fr/15489099",
    videoMatchTags: ["Vodka Averse Premium", "Vodka"],
    isFeatured: true,
  },
  {
    slug: "vodka-erable",
    name: "Vodka Érable",
    category: "spiritueux",
    subcategory: "vodka",
    description: "Subtilement sucrée aux notes d'érable authentique. L'essence du Québec dans chaque gorgée.",
    image: "/assets/products/CR_Vodka_Erable_750mL.png",
    abv: "40%",
    volume: "750 ml",
    websiteUrl: "https://www.cherryriver.ca/spiritueux/vodka-erable/",
    saqUrl: "https://www.saq.com/fr/14064873",
    videoMatchTags: ["Vodka Érable", "Vodka"],
  },
  {
    slug: "vodka-cerise",
    name: "Vodka Cerise",
    category: "spiritueux",
    subcategory: "vodka",
    description: "Arômes authentiques de cerises mûres. Parfait pour cocktails ou shots fruités.",
    image: null,
    abv: "40%",
    volume: "750 ml",
    websiteUrl: "https://www.cherryriver.ca/spiritueux/vodka-cerise/",
    videoMatchTags: ["Vodka Cerise", "Vodka"],
  },

  // ─── RHUMS ───────────────────────────────────────────────
  {
    slug: "rhum-ambre",
    name: "Rhum Ambré",
    category: "spiritueux",
    subcategory: "rhum",
    description: "Notes riches et caramélisées, vieilli pour une profondeur de caractère unique. Parfait pour cocktails tiki et dégustations.",
    image: "/assets/products/CR_RhumAmbre_750mL.png",
    abv: "40%",
    volume: "750 ml",
    websiteUrl: "https://www.cherryriver.ca/spiritueux/rhum-ambre/",
    saqUrl: "https://www.saq.com/fr/15303910",
    videoMatchTags: ["Rhum"],
    isFeatured: true,
  },
  {
    slug: "rhum-epice",
    name: "Rhum Épicé",
    category: "spiritueux",
    subcategory: "rhum",
    description: "Relevé d'épices chaudes pour des cocktails ou digestifs savoureux. Un caractère corsé et enveloppant.",
    image: "/assets/products/CR_RhumEpice.png",
    abv: "40%",
    volume: "750 ml",
    websiteUrl: "https://www.cherryriver.ca/spiritueux/rhum-epice/",
    saqUrl: "https://www.saq.com/fr/14954868",
    videoMatchTags: ["Rhum"],
  },

  // ─── TEQUILA ─────────────────────────────────────────────
  {
    slug: "tequila-silver",
    name: "Tequila Silver",
    category: "spiritueux",
    subcategory: "tequila",
    description: "Pure et cristalline, idéale pour shots et cocktails classiques. Agave sélectionné avec soin.",
    image: "/assets/products/CR_TequilaSilver_750mL.png",
    abv: "40%",
    volume: "750 ml",
    websiteUrl: "https://www.cherryriver.ca/spiritueux/tequila-silver/",
    saqUrl: "https://www.saq.com/fr/14954892",
    videoMatchTags: ["Tequila Silver", "Tequila"],
  },

  // ─── BOURBON ─────────────────────────────────────────────
  {
    slug: "bourbon-whiskey",
    name: "Bourbon Whiskey",
    category: "spiritueux",
    subcategory: "bourbon",
    description: "Notes boisées et vanillées pour revisiter vos classiques. Un bourbon artisanal signé Cherry River.",
    image: null,
    abv: "40%",
    volume: "750 ml",
    websiteUrl: "https://www.cherryriver.ca/spiritueux/bourbon-whiskey/",
    videoMatchTags: ["Bourbon"],
  },

  // ─── LIQUEURS ────────────────────────────────────────────
  {
    slug: "liqueur-amaretto",
    name: "Liqueur d'Amaretto",
    category: "liqueur",
    description: "Arômes d'amandes grillées et de vanille. Idéal pour cocktails ou en digestif.",
    image: "/assets/products/CR_Liqueur_Amaretto_750mL.jpg",
    abv: "26%",
    volume: "750 ml",
    websiteUrl: "https://www.cherryriver.ca/spiritueux/liqueur-amaretto/",
    saqUrl: "https://www.saq.com/fr/14989788",
    videoMatchTags: ["Liqueur Amaretto", "Amaretto"],
  },
  {
    slug: "liqueur-cafe",
    name: "Liqueur de Café",
    category: "liqueur",
    description: "Riche en arômes intenses de grain torréfié. Parfait pour l'Espresso Martini et autres créations chocolatées.",
    image: "/assets/lifestyle/curated/rhum-epice-cafe-1.png",
    abv: "23%",
    volume: "750 ml",
    websiteUrl: "https://www.cherryriver.ca/spiritueux/liqueur-de-cafe/",
    saqUrl: "https://www.saq.com/fr/14989809",
    videoMatchTags: ["Liqueur de Café"],
  },
  {
    slug: "liqueur-orange",
    name: "Liqueur d'Orange",
    category: "liqueur",
    description: "Zestes d'orange et douceur subtile. Parfait pour cocktails classiques comme le Cosmopolitan et la Margarita.",
    image: "/assets/products/CR_Liqueur_Orange_750mL.jpg",
    abv: "26%",
    volume: "750 ml",
    websiteUrl: "https://www.cherryriver.ca/spiritueux/liqueur-dorange/",
    saqUrl: "https://www.saq.com/fr/14989825",
    videoMatchTags: ["Triple Sec", "Liqueur d'orange"],
  },
  {
    slug: "liqueur-vanille",
    name: "Liqueur de Vanille",
    category: "liqueur",
    description: "Arômes gourmands et chaleureux de vanille pure. Parfait pour cocktails, desserts ou en digestif.",
    image: "/assets/products/CR_Liqueur_Vanille_750mL.jpg",
    abv: "25%",
    volume: "750 ml",
    websiteUrl: "https://www.cherryriver.ca/spiritueux/liqueur-de-vanille/",
    saqUrl: "https://www.saq.com/fr/14989796",
    videoMatchTags: ["Liqueur de vanille"],
  },
  {
    slug: "creme-coaticook",
    name: "Crème Alcoolisée de Crème Glacée Coaticook",
    category: "liqueur",
    subcategory: "creme",
    description: "Crème alcoolisée onctueuse élaborée à partir de la crème glacée emblématique de la Laiterie de Coaticook. Un mariage gourmand entre le savoir-faire laitier québécois et l'art de la distillation Cherry River.",
    tagline: "Le Québec en bouteille",
    image: "/assets/products/Coaticook_Vanille_750mL.png",
    abv: "16%",
    volume: "750 ml",
    saqUrl: "https://www.saq.com/fr/15521562",
    videoMatchTags: ["Crème Coaticook"],
    isFeatured: true,
  },

  // ─── RTD (Prêts-à-boire) ────────────────────────────────
  {
    slug: "gin-limonade-355",
    name: "Gin Limonade",
    category: "rtd",
    description: "Cocktail prêt à boire en canette — gin Cherry River et limonade artisanale. Pétillant, rafraîchissant, élaboré au Québec.",
    image: "/assets/products/cans/CherryRiver_GinLimon_355mL_FRAN.png",
    abv: "5%",
    volume: "355 ml",
    saqUrl: "https://www.saq.com/fr/15474217",
    videoMatchTags: ["Gin Limonade", "RTD"],
  },
  {
    slug: "orange-sanguine-framboises-355",
    name: "Orange Sanguine & Framboises",
    category: "rtd",
    description: "Cocktail prêt à boire en canette — orange sanguine et framboises. Une explosion fruitée et vibrante, élaborée au Québec.",
    image: "/assets/products/cans/CherryRiver_OrangeSang_355mL_FRAN.png",
    abv: "5%",
    volume: "355 ml",
    saqUrl: "https://www.saq.com/fr/15298014",
    videoMatchTags: ["Orange Sanguine", "RTD"],
  },
  {
    slug: "tropical-rich-rum-punch",
    name: "Tropical Rich Rum Punch",
    category: "rtd",
    subcategory: "rhum",
    description: "Cocktail prêt à boire — punch tropical au rhum ambré, fruits exotiques et épices. Élaboré au Québec par Cherry River.",
    image: "/assets/products/TropicalRichRumPunch_750mL.png",
    abv: "10%",
    volume: "750 ml",
    videoMatchTags: ["Rhum", "Punch"],
  },

  {
    slug: "limonade-vodka-citron-vert",
    name: "Limonade Vodka Citron Vert",
    category: "rtd",
    description: "Limonade non pétillante à la vodka et citron vert. Fraîcheur vive et naturelle, prête à servir.",
    image: "/assets/products/cans-na/Limonade_Non-petillante_Fran.png",
    abv: "5%",
    volume: "355 ml",
    videoMatchTags: ["Limonade", "RTD"],
  },

  // ─── MOCKTAILS (Canettes sans alcool) ────────────────────
  {
    slug: "amaretto-sour-sans-alcool",
    name: "Amaretto Sour Sans Alcool",
    category: "mocktail",
    description: "Toute la richesse de l'Amaretto Sour — amande, agrumes et douceur — sans une goutte d'alcool.",
    image: "/assets/products/cans-na/CR_AmarettoSour_355mL_SANS_ALCOOL_FRAN.png",
    abv: "0%",
    volume: "355 ml",
    videoMatchTags: ["Mocktail", "Amaretto Sour"],
  },
  {
    slug: "cosmopolitan-sans-alcool",
    name: "Cosmopolitan Sans Alcool",
    category: "mocktail",
    description: "Le classique Cosmopolitan revisité sans alcool. Canneberge, lime et une touche d'agrumes.",
    image: "/assets/products/cans-na/CR_Cosmo_355mL_SANS_ALCOOL_FRAN.png",
    abv: "0%",
    volume: "355 ml",
    videoMatchTags: ["Mocktail", "Cosmopolitan"],
  },
  {
    slug: "margarita-sans-alcool",
    name: "Margarita Sans Alcool",
    category: "mocktail",
    description: "L'esprit festif de la Margarita — lime, sel et fraîcheur — en version zéro alcool.",
    image: "/assets/products/cans-na/CR_Margarita_355mL_SANS_ALCOOL_FRAN.png",
    abv: "0%",
    volume: "355 ml",
    videoMatchTags: ["Mocktail", "Margarita"],
  },
  {
    slug: "melon-eau-lime-sans-alcool",
    name: "Melon, Eau & Lime Sans Alcool",
    category: "mocktail",
    description: "Melon d'eau frais et lime vive pour un mocktail désaltérant et léger.",
    image: "/assets/products/cans-na/CR_MelonEauLime_355mL_SANS_ALCOOL_FRAN.png",
    abv: "0%",
    volume: "355 ml",
    videoMatchTags: ["Mocktail", "Melon"],
  },
  {
    slug: "mojito-sans-alcool",
    name: "Mojito Sans Alcool",
    category: "mocktail",
    description: "Menthe fraîche, lime et bulles. Le Mojito classique en version sans alcool.",
    image: "/assets/products/cans-na/CR_Mojito_355mL_SANS_ALCOOL_FRAN.png",
    abv: "0%",
    volume: "355 ml",
    videoMatchTags: ["Mocktail", "Mojito"],
  },
  {
    slug: "orange-sanguine-sans-alcool",
    name: "Orange Sanguine Sans Alcool",
    category: "mocktail",
    description: "L'intensité de l'orange sanguine en mocktail fruité et vibrant.",
    image: "/assets/products/cans-na/CR_OrangeSanguine_355mL_SANS_ALCOOL_FRAN.png",
    abv: "0%",
    volume: "355 ml",
    videoMatchTags: ["Mocktail", "Orange Sanguine"],
  },
  {
    slug: "sangria-rouge-sans-alcool",
    name: "Sangria Rouge Sans Alcool",
    category: "mocktail",
    description: "Fruits rouges, épices douces et fraîcheur. La sangria festive en version zéro alcool.",
    image: "/assets/products/cans-na/CR_SangriaRouge_355mL_SANS_ALCOOL_FRAN.png",
    abv: "0%",
    volume: "355 ml",
    videoMatchTags: ["Mocktail", "Sangria"],
  },
  {
    slug: "paloma-sans-alcool",
    name: "Mocktail Paloma Sans Alcool",
    category: "mocktail",
    description: "Pamplemousse rose et lime pour un Paloma rafraîchissant sans alcool.",
    image: "/assets/products/cans-na/CR_MocktailPaloma_355mL_SANS_ALCOOL_FRAN.png",
    abv: "0%",
    volume: "355 ml",
    videoMatchTags: ["Mocktail", "Paloma"],
  },
  {
    slug: "petits-fruits-sans-alcool",
    name: "Mocktail Petits Fruits Sans Alcool",
    category: "mocktail",
    description: "Un bouquet de petits fruits — bleuets, framboises et mûres — en mocktail pétillant.",
    image: "/assets/products/cans-na/CR_MocktailPetitsFruits_355mL_SANS_ALCOOL_FRAN.png",
    abv: "0%",
    volume: "355 ml",
    videoMatchTags: ["Mocktail", "Petits Fruits"],
  },

  // ─── OPEMISKA ────────────────────────────────────────────
  {
    slug: "opemiska-gin-boreal",
    name: "Opemiska Gin Boréal",
    category: "collaboration",
    description: "Un gin inspiré par la forêt boréale québécoise. Botaniques nordiques, baies sauvages et épinette noire pour un caractère unique.",
    tagline: "L'esprit de la forêt boréale",
    image: "/assets/products/Ope_Gin_Boreal_750mL.png",
    abv: "43%",
    volume: "750 ml",
    saqUrl: "https://www.saq.com/fr/14545132",
    videoMatchTags: ["Gin Boréal Opemiska", "Gin"],
    isFeatured: true,
  },
  {
    slug: "opemiska-bleuets",
    name: "Opemiska Bleuets",
    category: "collaboration",
    description: "L'essence des bleuets sauvages du Québec capturée dans un gin nordique d'exception.",
    image: "/assets/products/Ope_Bleuets_750mL.png",
    abv: "40%",
    volume: "750 ml",
    saqUrl: "https://www.saq.com/fr/14758699",
    videoMatchTags: ["Opemiska", "Gin"],
  },
  {
    slug: "opemiska-fraise",
    name: "Opemiska Fraise",
    category: "collaboration",
    description: "Fraises d'été du Québec et botaniques boréaux pour un gin fruité et élégant.",
    image: "/assets/products/Ope_Fraise_750mL.png",
    abv: "40%",
    volume: "750 ml",
    saqUrl: "https://www.saq.com/fr/15095284",
    videoMatchTags: ["Opemiska", "Gin"],
  },
  {
    slug: "opemiska-liqueur-whisky",
    name: "Opemiska Liqueur de Whisky",
    category: "collaboration",
    description: "Le caractère du whisky rencontre la douceur d'une liqueur artisanale. Notes de caramel, vanille et bois fumé.",
    image: "/assets/products/Ope_LiqueurWhisky_750mL.png",
    abv: "30%",
    volume: "750 ml",
    saqUrl: "https://www.saq.com/fr/15303872",
    videoMatchTags: ["Opemiska", "Whisky"],
  },
];

export function getProductBySlug(slug: string): Product | undefined {
  return PRODUCTS_CATALOG.find((p) => p.slug === slug);
}

export function getAllSlugs(): string[] {
  return PRODUCTS_CATALOG.map((p) => p.slug);
}

export const CATEGORY_LABELS: Record<Product["category"], string> = {
  spiritueux: "Spiritueux",
  liqueur: "Liqueur",
  rtd: "Prêt-à-boire",
  mocktail: "Mocktail",
  mixer: "Mixer",
  opemiska: "Opemiska",
  collaboration: "Collaboration",
};
