export const rawVideos = [
      { id: "-Fk1EVpfxJY", title: "Le Mojito", spirit: "Rhum", desc: "Le meilleur mojito, tout simplement." },
      { id: "IEd4fWg6maA", title: "Le Old Fashioned", spirit: "Bourbon", desc: "Comment réussir le meilleur old fashioned." },
      { id: "-1KI8Az9NY4", title: "Le Cosmopolitan", spirit: "Vodka", desc: "Histoire et recette parfaite du classique." },
      { id: "l1tkDAwAECg", title: "Le Manhattan", spirit: "Whisky", desc: "La méthode pour un Manhattan impeccable." },
      { id: "aU2zgJoXbC8", title: "L'Espresso Martini", spirit: "Vodka", desc: "Vodka, tequila, rhum ou bourbon ?" },
      { id: "8YINLAgD6gk", title: "Le Tom Collins", spirit: "Gin", desc: "Le classique rafraîchissant, façon Cherry River." },
      { id: "LpvW7BBfrKI", title: "L'El Diablo", spirit: "Tequila", desc: "Savoureux et légèrement épicé." },
      { id: "VrLC_lFb7bQ", title: "La White Lady", spirit: "Gin", desc: "Le classique parfait pour le jour du gin." },
      { id: "5JW9BXD7h1c", title: "Le Lemon Drop Martini", spirit: "Vodka", desc: "Vif, acidulé et élégant." },
      { id: "Ir-dcqp6GTY", title: "L'Amaretto Sour", spirit: "Liqueur", desc: "L'amaretto sour revisité, sublimé." },
      { id: "iUZXegfqpnQ", title: "Le Hurricane", spirit: "Rhum", desc: "Le tiki de la Nouvelle-Orléans, à notre façon." },
      { id: "3dmdVhYFYwo", title: "Le Queen's Park Swizzle", spirit: "Rhum", desc: "Meilleur qu'un mojito ?" },
      { id: "yNdCHmLT9zI", title: "La Piña Colada", spirit: "Rhum", desc: "Classique contre version sans alcool." },
      { id: "eFNm8k8t110", title: "Le Clever Club", spirit: "Gin", desc: "Un délicieux cocktail au gin." },
      { id: "v-k1E9hxqH8", title: "Le Dawa", spirit: "Vodka", desc: "La caïpirinha kényane, miel et lime." },
      { id: "_u0zPo-sl54", title: "Le Royal Refresher", spirit: "Estival", desc: "Le cocktail parfait pour l'été." },
      { id: "MjHY3FGg0SI", title: "4 cocktails à la téquila", spirit: "Tequila", desc: "Pour célébrer le Cinco de Mayo." },
      { id: "1ZVrfVocjTc", title: "3 cocktails highball", spirit: "Technique", desc: "Trois idées de cocktails allongés." },
      { id: "R8FW6pfaMCw", title: "3 cocktails d'Halloween", spirit: "Édition spéciale", desc: "Trois cocktails d'Halloween qui valent le détour." },
      { id: "_3gqiF1wUWM", title: "Shake vs Stir", spirit: "Technique", desc: "Faut-il agiter ou remuer à la cuillère ?" }
    ];
